upra/config/routes.rb
Upra::Application.routes.draw do

  get "homes/index"

  resources :homes do 
    collection do
      get 'about_us'
      get 'projects'
      post 'our_mission'
      post 'how_to_join'
      post 'events'
      post 'all_content'
      get 'contact_us'
      get 'join_us'
    end
  end

  resource :users do 
  end

  resource :news do 
    get 'index'
  end

   root :to => 'homes#index'

end

upra/app/models/home.rb
class Home < ActiveRecord::Base
end

upra/app/models/news.rb
class News < ActiveRecord::Base
end

upra/app/models/user.rb
class User < ActiveRecord::Base
end

upra/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

upra/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

  def about_us
  end

  def join_us
  end

  def projects
  end

  def our_mission
  end

  def how_to_join
  end

  def contact_us
  end

  def events
  end

  def all_content
  end

  def show
  	@all_content = Home.all
  end

  def edit
  	@row = Home.find(params[:id])
  end

  def create

  end

  def new
  end

	def update
		@row = Home.find(params[:id])
		@row.update_attributes(params[:home])
		if @row.save
			redirect_to :action => :show
		end
	end
end

upra/app/controllers/news_controller.rb
class NewsController < ApplicationController

	def index
		@news = News.all
	end
	
end

upra/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
	end

	def edit
	end

	def update
	end

	def delete
	end

	def new
	end

	def create
		User.create(params[:user])
		redirect_to :action => :index, :controller => :homes
	end
	
end

upra/app/helpers/application_helper.rb
module ApplicationHelper
end

upra/app/helpers/homes_helper.rb
module HomesHelper
end

upra/app/helpers/news_helper.rb
module NewsHelper
end

upra/app/helpers/users_helper.rb
module UsersHelper
end

upra/app/views/homes/about_us.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--

-->
</style>
<link href="Css/Style_sheet.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center" valign="top" class="top_bg">
    <table width="907" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
      <td height="123" align="left" valign="middle">
        <%= image_tag "logo.png", :size => "906x78", :border => "0" %>
      </td>
      </tr>
      <tr>
        <td height="61" valign="middle" style="background:url(/assets/menubg.png) no-repeat;height:61px;">
      <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="menu">
        <tr>
        <td width="127" height="50" align="center"><a href="index.html" >Home</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'About us', about_us_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Projects', projects_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="http://www.jagomumbairadio.com">Radio</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="News.html">News</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="Donations.html">Donations</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Contact us',  contact_us_homes_path %></td>
        
        </tr>
      </table>

      </td>
       </tr>
      <tr>
      <td align="center" valign="top" >
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td align="center" valign="bottom"><%= image_tag "contbox_top.png", :size => "907x12", :border => "0" %></td>
              </tr>
              <tr>
                <td align="center" valign="top" class="contbox_mid" >
                  <table width="880px" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                        <td class="head_text">ABOUT US</td>
                      </tr>
                      <tr>
                        <td class="hr" height="15px">&nbsp;</td>
                      </tr>
                      <tr>
                        <td class="cont" style="padding-top:10px;" >
                        <div style="float:right;width:110px;height:110px;"><%= image_tag "UPRA.png", :size => "100x100", :align => "right" %></div>
                        Union Park Residents Association is a voluntary organization / association of the Union Park Residents, registered with the BMC as ALM No.104, Aug 2,                         2002, as a Society with the Registrar of Societies, Registration No. 1318 dt. August 9, 2004, and with the Charities Commission, Regn. No. F-27605 DT.                         March 31, 2005.
                        <br /> <br /> 
The Union Park Residents Association is representative of a residential area comprising of 42 buildings and 8 bungalows spread over 5 lanes (Roads No. 3, 4, 5, Deccan Road and Govind Ghag Marg - Union Park Main Road).<br /> <br /> 
 <div style="float:left;width:187px;height:113px;"><%= image_tag "abt_1.jpg", :size => "177x108", :align => "left" %></div>
We have a Managing Committee of 11 members that holds monthly meetings to discuss and decide on the issues and agenda regarding various civic, traffic & environmental issues facing our residents. Annual AGMs also held regularly.<br /> <br /> 
                       

The objective of the Association is to create a clean and green environment along with improved civic amenities for our residents; besides this is a platform for our Residents to come together in harmony. Since inception the Association has worked closely with the MCGM, Police, Traffic Police, Elected Representatives resulting in better civic amenities for Union Park.

                        </td>
                      </tr>
                        <tr>
                        <td>&nbsp;</td>
                      </tr>
                        <tr>
                        <td class="head_text2">OUR MISSION</td>
                      </tr>
                      <tr>
                        <td class="hr" height="15px">&nbsp;</td>
                      </tr>
                      <tr>
                        <td class="cont">
                        <div style="float:right;width:200px;height:160px;"><%= image_tag "our_mis.jpg", :size => "180x155", :align => "right" %></div>
                        
                        We as citizens of Mumbai are responsible to continuously learn/train and prepare ourselves and other fellow-citizens to conduct ourselves suitably and to proactively assist Brihanmumbai Mahanagarpalika, the Government and other such organizations genuinely concerned with Mumbai's welfare, to develop and maintain Mumbai as a clean, modern and progressive, environmentally safe, peaceful and healthy place to live and work in. Create a movement 'Jago Mumbai' by implementing and practicing first what we preach.</td>
                    </tr>
                      
                      <tr>
                        <td>&nbsp;</td>
                      </tr>
                        <tr>
                        <td class="head_text2">How To Join</td>
                      </tr>
                      <tr>
                        <td class="hr" height="15px">&nbsp;</td>
                      </tr>
                      <tr>
                        <td class="cont">If you live here or own a business here you are a member. All residents - and that includes renters - in the Union Park area are welcome to participate. But watch out: if you are especially interested in an issue you may be asked to head a committee!</td>
                    </tr>
                    </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top"><%= image_tag "contbox_bot.png", :size => "907x12", :border => "0" %></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
              </tr>
            </table>
           </td>
      </tr>
      
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
  </td>
  </tr>
  <tr>
    <td class="bot_bg">&nbsp;</td>
  </tr>
</table>


<map name="Map" id="map">
  <area shape="rect" coords="227,15,313,30" href="#" />
</map>

<map name="Map2" id="map2">

  <area shape="rect" coords="2,4,38,25" href="#" />
  <area shape="rect" coords="64,3,104,24" href="#" />
  <area shape="rect" coords="131,3,168,26" href="#" />
  <area shape="rect" coords="194,1,232,27" href="#" />
  <area shape="rect" coords="251,0,311,27" href="#" />
</map>

</body>
</html>

upra/app/views/homes/contact_us.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--

-->
</style>
<link href="Css/Style_sheet.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center" valign="top" class="top_bg">
    <table width="907" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
      <td height="123" align="left" valign="middle">
        <%= image_tag "logo.png", :size => "906x78", :border => "0" %>
      </td>
      </tr>
      <tr>
        <td height="61" valign="middle" style="background:url(/assets/menubg.png) no-repeat;height:61px;">
      <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="menu">
        <tr>
        <td width="127" height="50" align="center"><a href="index.html" >Home</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'About us', about_us_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Projects', projects_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="http://www.jagomumbairadio.com">Radio</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="News.html">News</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="Donations.html">Donations</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Contact us',  contact_us_homes_path %></td>
        
        </tr>
      </table>

      </td>
       </tr>
      <tr>
      <td align="center" valign="top" >
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td align="center" valign="bottom"><%= image_tag "contbox_top.png", :size => "907x12", :border => "0" %></td>
              </tr>
              <tr>
                <td align="center" valign="top" class="contbox_mid" >
                  <table width="880px" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                      </tr>
                      <tr>
                        <td class="hr" height="15px">&nbsp;</td>
                      </tr>                                                                                    
                    </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top"><%= image_tag "contbox_bot.png", :size => "907x12", :border => "0" %></td>
                <div id="divbox">
<div style="float:right;padding-right:25px;padding-top:50px;"><img src="images/contact_img.gif" height="256" width="210"></div>
<p class="green" style="padding-top:10px;"><b>UNION PARK RESIDENTS ASSOCIATION</b></p>
<p class="content"><b>Contact Person :</b><br> <span class="names"><b>Mr. Navin Chandra,</b></span> <br> Chairman, Community Development Projects<br> <b>Project Office :</b><br> Sealine CHS Ltd., 16 Union Park,  Khar (West), Mumbai Â– 400 052. (INDIA)<br> <b>Tel.: </b>+ 91 22 Â– 2605 9320 / 4006 0026 &nbsp;&nbsp;
              <b>Telefax :</b> + 91 22 Â– 2646 5264 <br> <b>SMS :</b> + 91 98192 86386 <br> <b>Email :</b> <a href="*">navinchandra.upra@gmail.com</a> /
             <a href="*">sealinechs@gmail.com</a> <br> <br> <b>"JAGO MUMBAI" Radio Station :</b> <br> Seahill CHS Ltd. 31/32 Union Park, Khar (West), Mumbai Â– 400 052. (INDIA)                         <br> <b>Tel.: </b>+ 91 22 Â– 4266 3000 / 4266 4000 &nbsp;&nbsp;
              <b>Email :</b> <a href="*">upra.jagomumbai@gmail.com</a> <br> <b>Website :</b> <a href="www.uprajagomumbai.com">www.uprajagomumbai.com </a>&nbsp; <b>/</b>&nbsp;
                         <a href="www.jagomumbairadio.com"> www.jagomumbairadio.com</a> <br><br> <b>Contact Person :</b> <br> <span class="names"> Bharati Kakkad - 9820043533 /
             Surekha Kotwani - 9821864894 /
             Nitin Makasare - 9769696562 </span></p>
</div>
              </tr>
              <tr>
                <td>&nbsp;</td>
              </tr>
            </table>
           </td>
      </tr>
      
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
  </td>
  </tr>
  <tr>
    <td class="bot_bg">&nbsp;</td>
  </tr>
</table>


<map name="Map" id="map">
  <area shape="rect" coords="227,15,313,30" href="#" />
</map>

<map name="Map2" id="map2">

  <area shape="rect" coords="2,4,38,25" href="#" />
  <area shape="rect" coords="64,3,104,24" href="#" />
  <area shape="rect" coords="131,3,168,26" href="#" />
  <area shape="rect" coords="194,1,232,27" href="#" />
  <area shape="rect" coords="251,0,311,27" href="#" />
</map>

</body>
</html>

upra/app/views/homes/edit.html.erb
<%= form_for @row do |f|%>
	<%= f.label :subject, "Subject: "%>
	<%= f.object.subject%>
	<%= f.label :content%>
	<%= f.text_area :content%>
	<%= f.submit%>
<%end%>

upra/app/views/homes/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--

-->
</style>
<link href="Css/Style_sheet.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center" valign="top" class="top_bg">
    <table width="907" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
      <td height="123" colspan="3" align="left" valign="middle">
        <%= image_tag "logo.png", :size => "906x78", :border => "0" %>
      </td>
      </tr>
      <tr>
        <td height="61" colspan="3" valign="middle" style="background:url(/assets/menubg.png) no-repeat;height:61px;">
      <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="menu">
        <tr>
        <td width="127" height="50" align="center"><%= link_to 'Home', '#' %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'About us', about_us_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Projects', projects_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="http://www.jagomumbairadio.com">Radio</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'News', news_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="Donations.html">Donations</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Contact us',  contact_us_homes_path %></td>
        
        </tr>
      </table>

      </td>
       </tr>
      <tr>
      <td height="30" colspan="3">&nbsp;</td>
      </tr>
      <tr>
      <td width="330px" align="center" >
      <a href="#"><%= image_tag "donate_bt.png", :size => "195x60", :border => "0" %></a><br />
      <div id="div_dnttyps" style="padding-top:08px;">
            <%= image_tag "cards.png", :size => "314x26", :border => "0", :align => "middle", :usemap=>"#Map2" %>
      </div>
    </td>
      <td width="18" rowspan="3">&nbsp;</td>
      <td width="559" rowspan="2" align="left" valign="top" >
         <table width="100%" border="0" cellpadding="0" cellspacing="0">
          <tr>
          <td colspan="3" >
           <span class="head_text" >Projects</span>
           <div style="padding-top:5px;padding-bottom:10px">
           <%= image_tag "hr.jpg", :size => "556x2"%> 
            </div></td>
          </tr>
          <tr>
          <td width="268"><%= link_to image_tag( "alm1.jpg", :size => "268x165, :border => 0"), '#'%></td>
          <td width="23">&nbsp; </td>
          <td width="268"><%= link_to image_tag( "fm.jpg", :size => "268x165, :border => 0"), '#'%></td>
          </tr>
          <tr>
          <td height="23" colspan="3">&nbsp;</td>
          </tr>
          <tr>
          <td><%= link_to image_tag( "upra.jpg", :size => "268x165", :border => "0"), '#' %></td>
          <td>&nbsp;</td>
          <td><%= link_to image_tag( "beti.jpg", :size => "268x165", :border => "0"), '#'%></td>
          </tr>
          </table>  
        </td>
      </tr>
      <tr>
      <td align="left" valign="top" style="padding-top:10px;">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="47"  class="leftboxtop" >
                <span class="leftboxtext" >Our Misssion</span></td>
              </tr>
              <tr >
                <td class="leftboxmid" >
         <div id="left_imgbox"> <%= image_tag "img1.jpg", :size => "67x114", :align => "right"%></div>  
         <div id="left_textbox"><%= Home.find_by_subject("Our Misssion").try(:content).try(:html_safe)%> </div>   
        </td>
              </tr>
              <tr>
                <td  ><%= image_tag "img1.jpg", :size => "330x36", :border => "0", :usemap => "#Map"%></td>
              </tr>
            </table>
      </td>
      </tr>
      <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="88" align="right" valign="bottom" class="email_bg"  >
          <table width="68%" border="0" align="right" cellpadding="0" cellspacing="0" >
          <tr>
          <td height="59" colspan="2">&nbsp;</td>
          </tr>
          <tr>
            <td height="29" align="left" valign="top" >
              <%= form_tag users_path  do %> 
                <% text_field_tag  "user[email]","", :placeholder => "Your Email" %>
              <%end%>
            <td width="50" height="26" align="center" valign="middle" > 
          <%= link_to image_tag("bt.png", :size => "11x17", :border => "0"), '#', :onclick => "$('form').submit();"%>  
          </td>
           </tr>
        </table>
            </td>
        <td>&nbsp;</td>
        <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
          <td width="132" ><img src="/assets/event_main.gif" width="132" height="88" /></td>
          <td class="event_bg"> 
                    
                    <marquee bgcolor="#FFFFFF" scrollamount="2" direction="up" loop="true" width="400px"  height="70px"> 
                    <%= Home.find_by_subject("Events").try(:content).try(:html_safe)%>
                    
                    </marquee>
                    
                    </td>
          </tr>
        </table>
           </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>
       <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="47"  class="leftboxtop">
                <span class="leftboxtext" >How to Join</span>
                </td>
              </tr>
              <tr >
                <td class="leftboxmid" >
         <div id="left_imgbox"> <img src="/assets/img2.jpg" width="67" height="114" align="right"/></div>  
         <div id="left_textbox1"><%= Home.find_by_subject("How to Join").content.html_safe rescue nil%> </div>    
        </td>
              </tr>
              <tr>
                <td ><img src="/assets/leftbox_bot.png" width="330" height="36" border="0" usemap="#Map"  /></td>
              </tr>
            </table>
      </td>
        <td>&nbsp;</td>
        <td align="left" valign="top">
              <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="556" height="231" id="banner" align="middle">
        <param name="movie" value="flash/banner.swf" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#ffffff" />
        <param name="play" value="true" />
        <param name="loop" value="true" />
        <param name="wmode" value="transparent" />
        <param name="scale" value="showall" />
        <param name="menu" value="true" />
        <param name="devicefont" value="false" />
        <param name="salign" value="" />
        <param name="allowScriptAccess" value="sameDomain" />
        <!--[if !IE]>-->
  <object type="application/x-shockwave-flash" data="flash/banner.swf" width="556" height="231">
          <param name="movie" value="banner.swf" />
          <param name="quality" value="high" />
          <param name="bgcolor" value="#ffffff" />
          <param name="play" value="true" />
          <param name="loop" value="true" />
          <param name="wmode" value="transparent" />
          <param name="scale" value="showall" />
          <param name="menu" value="true" />
          <param name="devicefont" value="false" />
          <param name="salign" value="" />
          <param name="allowScriptAccess" value="sameDomain" />
        <!--<![endif]-->
          <a href="http://www.adobe.com/go/getflash">
            <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
          </a>
        <!--[if !IE]>-->
        </object>
        <!--<![endif]-->
      </object>
            </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </td>
  </tr>
  <tr>
    <td class="bot_bg">&nbsp;</td>
  </tr>
</table>


<map name="Map" id="map">
  <area shape="rect" coords="227,15,313,30" href="#" />
</map>

<map name="Map2" id="map2">

  <area shape="rect" coords="2,4,38,25" href="#" />
  <area shape="rect" coords="64,3,104,24" href="#" />
  <area shape="rect" coords="131,3,168,26" href="#" />
  <area shape="rect" coords="194,1,232,27" href="#" />
  <area shape="rect" coords="251,0,311,27" href="#" />
</map>

</body>
</html>

upra/app/views/homes/show.html.erb
<table border="1">
	<tr>
		<th>subject</th>
		<th>content</th>
		<th>Action</th>
	</tr>
	<%@all_content.each do |content|%>
		<tr>
			<td><%= content.subject%></td>
			<td><%= content.content%></td>
			<td><%= link_to "Edit", edit_home_path(content)%></td>
		</tr>
	<%end%>
</table>

upra/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upra</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

upra/app/views/news/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--

-->
</style>
<link href="Css/Style_sheet.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center" valign="top" class="top_bg">
    <table width="907" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
      <td height="123" align="left" valign="middle">
        <%= image_tag "logo.png", :size => "906x78", :border => "0" %>
      </td>
      </tr>
      <tr>
        <td height="61" valign="middle" style="background:url(/assets/menubg.png) no-repeat;height:61px;">
      <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" id="menu">
        <tr>
        <td width="127" height="50" align="center"><a href="index.html" >Home</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'About us', about_us_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Projects', projects_homes_path %></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="http://www.jagomumbairadio.com">Radio</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="News.html">News</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><a href="Donations.html">Donations</a></td>
        <td width="2" align="center"><%= image_tag "sepr.png", :size => "1x30" %></td>
        <td width="127" align="center"><%= link_to 'Contact us',  contact_us_homes_path %></td>
        
        </tr>
      </table>

      </td>
       </tr>
      <tr>
      <td align="center" valign="top" >
             <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td align="center" valign="bottom"><%= image_tag "contbox_top.png", :size => "907x12", :border => "0" %></td>
              </tr>
              <tr>
                <td align="center" valign="top" class="contbox_mid" >
                  <table width="880px" border="0" align="center" cellpadding="0" cellspacing="0">
                    <% @news.each do |value| %> 
                      <tr>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td class="head_text2"><%= value.heading%></td>
                      </tr>
                      <tr>
                        <td class="hr" height="15px">&nbsp;</td>
                      </tr>
                      <tr>
                        <td class="cont">
                        <div style="float:right;width:200px;height:160px;"><%= image_tag "our_mis.jpg", :size => "180x155", :align => "right" %></div>
                        <%= value.body%>
                        </td>
                    </tr> 
                    <%end%>                                                                        
                  </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top"><%= image_tag "contbox_bot.png", :size => "907x12", :border => "0" %></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
              </tr>
            </table>
           </td>
      </tr>
      
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
  </td>
  </tr>
  <tr>
    <td class="bot_bg">&nbsp;</td>
  </tr>
</table>


<map name="Map" id="map">
  <area shape="rect" coords="227,15,313,30" href="#" />
</map>

<map name="Map2" id="map2">

  <area shape="rect" coords="2,4,38,25" href="#" />
  <area shape="rect" coords="64,3,104,24" href="#" />
  <area shape="rect" coords="131,3,168,26" href="#" />
  <area shape="rect" coords="194,1,232,27" href="#" />
  <area shape="rect" coords="251,0,311,27" href="#" />
</map>

</body>
</html>